spring:
  profiles:
    active:
    - test # 默认使用环境是 test
---
server:
  port: 8001 # 服务提供者提供服务的端口
spring:
  application:
    name: USER-PROVIDER # 服务名，注意大写，中间一定不能有"下划线"
  profiles: provider # 当前环境的代号，若要使用该环境需要该参数
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/ # Eureka 服务注册中心的服务地址
---
server:
  port: 9001 # 服务提供者提供服务的端口
eureka:
  client:
    register-with-eureka: false # 是否注册到注册中心，在注册中心显示
    service-url:
      defaultZone: http://localhost:7001/eureka/ # 要注册到的注册中心地址
spring:
  profiles: ribbon # 当前环境的代号，若要使用该环境需要该参数
---
server:
  port: 9002 # 服务提供者提供服务的端口
eureka:
  client:
    register-with-eureka: false # 是否注册到注册中心，在注册中心显示
    service-url:
      defaultZone: http://localhost:7001/eureka/ # 要注册到的注册中心地址
feign:
  hystrix:
    enabled: true # 开启断路器
spring:
  profiles: feign # 当前环境的代号，若要使用该环境需要该参数
---
server:
  port: 9527 # 服务提供者提供服务的端口
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
zuul:
  ignored-services: '*' # 忽略所有的服务，意思除了通过使用路由方式，直接调用服务的方式将被无视
  prefix: '/xielei' # 前缀，统一一个项目的路径，更规范
  routes:
    xl.serviceId: user-provider
    xl.path: /user/**  # 替代掉路由和具体的服务名
spring:
  application:
    name: MICROSERVICE-ZUUL # 显示在服务注册中心的名字
  profiles: zuul # 当前环境的代号，若要使用该环境需要该参数
